<a href="https://www.kaggle.com/code/abuhasan18/mlb-2-class-5-assignment?scriptVersionId=346677302" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv

# import libraries

In [2]:
import numpy as np
import pandas as pd

In [3]:
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

In [4]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
tips.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [6]:
tips.sample(5)

     total_bill   tip     sex smoker   day    time  size
143       27.05  5.00  Female     No  Thur   Lunch     6
65        20.08  3.15    Male     No   Sat  Dinner     3
102       44.30  2.50  Female    Yes   Sat  Dinner     3
4         24.59  3.61  Female     No   Sun  Dinner     4
218        7.74  1.44    Male    Yes   Sat  Dinner     2

In [7]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [8]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [9]:
tips.shape

(244, 7)

In [10]:
(tips.isnull().sum()/tips.shape[0])*100

total_bill    0.0
tip           0.0
sex           0.0
smoker        0.0
day           0.0
time          0.0
size          0.0
dtype: float64

In [11]:
tips[tips.duplicated(keep=False)]

     total_bill  tip     sex smoker   day   time  size
198        13.0  2.0  Female    Yes  Thur  Lunch     2
202        13.0  2.0  Female    Yes  Thur  Lunch     2

# create np-array

# 1. create 1D, 2D, 3D and 4D array using np.array()

In [12]:
oneD=np.array([1,2,3,4])
twoD=np.array([[1,2,3,4]])
print(oneD.ndim)
print(twoD.ndim)

1
2

In [13]:
threeD=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
threeD.ndim

3

In [14]:

fourD = np.array([
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]]
    ],
    [
        [[9, 10], [11, 12]],
        [[13, 14], [15, 16]]
    ]
])
fourD.ndim

4

# create 1D, 2D, 3D and 4D array using arange() and reshape()

In [15]:
arr1=np.arange(1)
print(arr1)
print("number of dimention=",arr1.ndim)

[0]
number of dimention= 1

In [16]:
arr2=np.arange(16).reshape(4,4)
print(arr2)
print("Number of dimention=",arr2.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Number of dimention= 2

In [17]:
arr3=np.arange(27).reshape(3,3,3)
print(arr3)
print("Number of dimention=",arr3.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Number of dimention= 3

In [18]:
arr4=np.arange(256).reshape(4,4,4,4)
print(arr4)
print("Number of dimention=",arr4.ndim)

[[[[  0   1   2   3]
   [  4   5   6   7]
   [  8   9  10  11]
   [ 12  13  14  15]]

  [[ 16  17  18  19]
   [ 20  21  22  23]
   [ 24  25  26  27]
   [ 28  29  30  31]]

  [[ 32  33  34  35]
   [ 36  37  38  39]
   [ 40  41  42  43]
   [ 44  45  46  47]]

  [[ 48  49  50  51]
   [ 52  53  54  55]
   [ 56  57  58  59]
   [ 60  61  62  63]]]


 [[[ 64  65  66  67]
   [ 68  69  70  71]
   [ 72  73  74  75]
   [ 76  77  78  79]]

  [[ 80  81  82  83]
   [ 84  85  86  87]
   [ 88  89  90  91]
   [ 92  93  94  95]]

  [[ 96  97  98  99]
   [100 101 102 103]
   [104 105 106 107]
   [108 109 110 111]]

  [[112 113 114 115]
   [116 117 118 119]
   [120 121 122 123]
   [124 125 126 127]]]


 [[[128 129 130 131]
   [132 133 134 135]
   [136 137 138 139]
   [140 141 142 143]]

  [[144 145 146 147]
   [148 149 150 151]
   [152 153 154 155]
   [156 157 158 159]]

  [[160 161 162 163]
   [164 165 166 167]
   [168 169 170 171]
   [172 173 174 175]]

  [[176 177 178 179]
   [180 181 182 183]
   [184 185 186 187]
   [188 189 190 191]]]


 [[[192 193 194 195]
   [196 197 198 199]
   [200 201 202 203]
   [204 205 206 207]]

  [[208 209 210 211]
   [212 213 214 215]
   [216 217 218 219]
   [220 221 222 223]]

  [[224 225 226 227]
   [228 229 230 231]
   [232 233 234 235]
   [236 237 238 239]]

  [[240 241 242 243]
   [244 245 246 247]
   [248 249 250 251]
   [252 253 254 255]]]]
Number of dimention= 4

# create array using ones and zeros

In [19]:
one=np.ones((4,4))
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
zero=np.zeros((4,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# using random

In [21]:
np.random.random((3,4))

array([[0.8691435 , 0.8105641 , 0.58407442, 0.31124494],
       [0.05824778, 0.43331038, 0.29798068, 0.19470215],
       [0.37909487, 0.92389143, 0.04995856, 0.26029392]])

# using linspace

In [22]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

# create 1D array of tip from tips dataframe

In [23]:
tips.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [24]:
tips['total_bill'].to_numpy()

array([16.99, 10.34, 21.01, 23.68, 24.59, 25.29,  8.77, 26.88, 15.04,
       14.78, 10.27, 35.26, 15.42, 18.43, 14.83, 21.58, 10.33, 16.29,
       16.97, 20.65, 17.92, 20.29, 15.77, 39.42, 19.82, 17.81, 13.37,
       12.69, 21.7 , 19.65,  9.55, 18.35, 15.06, 20.69, 17.78, 24.06,
       16.31, 16.93, 18.69, 31.27, 16.04, 17.46, 13.94,  9.68, 30.4 ,
       18.29, 22.23, 32.4 , 28.55, 18.04, 12.54, 10.29, 34.81,  9.94,
       25.56, 19.49, 38.01, 26.41, 11.24, 48.27, 20.29, 13.81, 11.02,
       18.29, 17.59, 20.08, 16.45,  3.07, 20.23, 15.01, 12.02, 17.07,
       26.86, 25.28, 14.73, 10.51, 17.92, 27.2 , 22.76, 17.29, 19.44,
       16.66, 10.07, 32.68, 15.98, 34.83, 13.03, 18.28, 24.71, 21.16,
       28.97, 22.49,  5.75, 16.32, 22.75, 40.17, 27.28, 12.03, 21.01,
       12.46, 11.35, 15.38, 44.3 , 22.42, 20.92, 15.36, 20.49, 25.21,
       18.24, 14.31, 14.  ,  7.25, 38.07, 23.95, 25.71, 17.31, 29.93,
       10.65, 12.43, 24.08, 11.69, 13.42, 14.26, 15.95, 12.48, 29.8 ,
        8.52, 14.52, 11.38, 22.82, 19.08, 20.27, 11.17, 12.26, 18.26,
        8.51, 10.33, 14.15, 16.  , 13.16, 17.47, 34.3 , 41.19, 27.05,
       16.43,  8.35, 18.64, 11.87,  9.78,  7.51, 14.07, 13.13, 17.26,
       24.55, 19.77, 29.85, 48.17, 25.  , 13.39, 16.49, 21.5 , 12.66,
       16.21, 13.81, 17.51, 24.52, 20.76, 31.71, 10.59, 10.63, 50.81,
       15.81,  7.25, 31.85, 16.82, 32.9 , 17.89, 14.48,  9.6 , 34.63,
       34.65, 23.33, 45.35, 23.17, 40.55, 20.69, 20.9 , 30.46, 18.15,
       23.1 , 15.69, 19.81, 28.44, 15.48, 16.58,  7.56, 10.34, 43.11,
       13.  , 13.51, 18.71, 12.74, 13.  , 16.4 , 20.53, 16.47, 26.59,
       38.73, 24.27, 12.76, 30.06, 25.89, 48.33, 13.27, 28.17, 12.9 ,
       28.15, 11.59,  7.74, 30.14, 12.16, 13.42,  8.58, 15.98, 13.42,
       16.27, 10.09, 20.45, 13.28, 22.12, 24.01, 15.69, 11.61, 10.77,
       15.53, 10.07, 12.6 , 32.83, 35.83, 29.03, 27.18, 22.67, 17.82,
       18.78])

# create 2D array of tip and total_bill form tips dataframe

In [25]:
tips[['total_bill','tip']].to_numpy()

array([[16.99,  1.01],
       [10.34,  1.66],
       [21.01,  3.5 ],
       [23.68,  3.31],
       [24.59,  3.61],
       [25.29,  4.71],
       [ 8.77,  2.  ],
       [26.88,  3.12],
       [15.04,  1.96],
       [14.78,  3.23],
       [10.27,  1.71],
       [35.26,  5.  ],
       [15.42,  1.57],
       [18.43,  3.  ],
       [14.83,  3.02],
       [21.58,  3.92],
       [10.33,  1.67],
       [16.29,  3.71],
       [16.97,  3.5 ],
       [20.65,  3.35],
       [17.92,  4.08],
       [20.29,  2.75],
       [15.77,  2.23],
       [39.42,  7.58],
       [19.82,  3.18],
       [17.81,  2.34],
       [13.37,  2.  ],
       [12.69,  2.  ],
       [21.7 ,  4.3 ],
       [19.65,  3.  ],
       [ 9.55,  1.45],
       [18.35,  2.5 ],
       [15.06,  3.  ],
       [20.69,  2.45],
       [17.78,  3.27],
       [24.06,  3.6 ],
       [16.31,  2.  ],
       [16.93,  3.07],
       [18.69,  2.31],
       [31.27,  5.  ],
       [16.04,  2.24],
       [17.46,  2.54],
       [13.94,  3.06],
       [ 9.68,  1.32],
       [30.4 ,  5.6 ],
       [18.29,  3.  ],
       [22.23,  5.  ],
       [32.4 ,  6.  ],
       [28.55,  2.05],
       [18.04,  3.  ],
       [12.54,  2.5 ],
       [10.29,  2.6 ],
       [34.81,  5.2 ],
       [ 9.94,  1.56],
       [25.56,  4.34],
       [19.49,  3.51],
       [38.01,  3.  ],
       [26.41,  1.5 ],
       [11.24,  1.76],
       [48.27,  6.73],
       [20.29,  3.21],
       [13.81,  2.  ],
       [11.02,  1.98],
       [18.29,  3.76],
       [17.59,  2.64],
       [20.08,  3.15],
       [16.45,  2.47],
       [ 3.07,  1.  ],
       [20.23,  2.01],
       [15.01,  2.09],
       [12.02,  1.97],
       [17.07,  3.  ],
       [26.86,  3.14],
       [25.28,  5.  ],
       [14.73,  2.2 ],
       [10.51,  1.25],
       [17.92,  3.08],
       [27.2 ,  4.  ],
       [22.76,  3.  ],
       [17.29,  2.71],
       [19.44,  3.  ],
       [16.66,  3.4 ],
       [10.07,  1.83],
       [32.68,  5.  ],
       [15.98,  2.03],
       [34.83,  5.17],
       [13.03,  2.  ],
       [18.28,  4.  ],
       [24.71,  5.85],
       [21.16,  3.  ],
       [28.97,  3.  ],
       [22.49,  3.5 ],
       [ 5.75,  1.  ],
       [16.32,  4.3 ],
       [22.75,  3.25],
       [40.17,  4.73],
       [27.28,  4.  ],
       [12.03,  1.5 ],
       [21.01,  3.  ],
       [12.46,  1.5 ],
       [11.35,  2.5 ],
       [15.38,  3.  ],
       [44.3 ,  2.5 ],
       [22.42,  3.48],
       [20.92,  4.08],
       [15.36,  1.64],
       [20.49,  4.06],
       [25.21,  4.29],
       [18.24,  3.76],
       [14.31,  4.  ],
       [14.  ,  3.  ],
       [ 7.25,  1.  ],
       [38.07,  4.  ],
       [23.95,  2.55],
       [25.71,  4.  ],
       [17.31,  3.5 ],
       [29.93,  5.07],
       [10.65,  1.5 ],
       [12.43,  1.8 ],
       [24.08,  2.92],
       [11.69,  2.31],
       [13.42,  1.68],
       [14.26,  2.5 ],
       [15.95,  2.  ],
       [12.48,  2.52],
       [29.8 ,  4.2 ],
       [ 8.52,  1.48],
       [14.52,  2.  ],
       [11.38,  2.  ],
       [22.82,  2.18],
       [19.08,  1.5 ],
       [20.27,  2.83],
       [11.17,  1.5 ],
       [12.26,  2.  ],
       [18.26,  3.25],
       [ 8.51,  1.25],
       [10.33,  2.  ],
       [14.15,  2.  ],
       [16.  ,  2.  ],
       [13.16,  2.75],
       [17.47,  3.5 ],
       [34.3 ,  6.7 ],
       [41.19,  5.  ],
       [27.05,  5.  ],
       [16.43,  2.3 ],
       [ 8.35,  1.5 ],
       [18.64,  1.36],
       [11.87,  1.63],
       [ 9.78,  1.73],
       [ 7.51,  2.  ],
       [14.07,  2.5 ],
       [13.13,  2.  ],
       [17.26,  2.74],
       [24.55,  2.  ],
       [19.77,  2.  ],
       [29.85,  5.14],
       [48.17,  5.  ],
       [25.  ,  3.75],
       [13.39,  2.61],
       [16.49,  2.  ],
       [21.5 ,  3.5 ],
       [12.66,  2.5 ],
       [16.21,  2.  ],
       [13.81,  2.  ],
       [17.51,  3.  ],
       [24.52,  3.48],
       [20.76,  2.24],
       [31.71,  4.5 ],
       [10.59,  1.61],
       [10.63,  2.  ],
       [50.81, 10.  ],
       [15.81,  3.16],
       [ 7.25,  5.15],
       [31.85,  3.18],
       [16.82,  4.  ],
       [32.9 ,  3.11],
       [17.89,  2.  ],
       [14.48,  2.  ],
       [ 9.6 ,  4.  ],
       [34.63,  3.55],
       [34.65,  3.68],
       [23.33,  5.65],
       [45.35,  3.5 ],
       [23.17,  6.5 ],
       [40.55,  3.  ],
       [20.69,  5.  ],
       [20.9 ,  3.5 ],
       [30.46,  2.  ],
       [18.15,  3.5 ],
       [23.1 ,  4.  ],
       [15.69,  1.5 ],
       [19.81,  4.19],
       [28.44,  2.56],
       [15.48,  2.02],
       [16.58,  4.  ],
       [ 7.56,  1.44],
       [10.34,  2.  ],
       [43.11,  5.  ],
       [13.  ,  2.  ],
       [13.51,  2.  ],
       [18.71,  4.  ],
       [12.74,  2.01],
       [13.  ,  2.  ],
       [16.4 ,  2.5 ],
       [20.53,  4.  ],
       [16.47,  3.23],
       [26.59,  3.41],
       [38.73,  3.  ],
       [24.27,  2.03],
       [12.76,  2.23],
       [30.06,  2.  ],
       [25.89,  5.16],
       [48.33,  9.  ],
       [13.27,  2.5 ],
       [28.17,  6.5 ],
       [12.9 ,  1.1 ],
       [28.15,  3.  ],
       [11.59,  1.5 ],
       [ 7.74,  1.44],
       [30.14,  3.09],
       [12.16,  2.2 ],
       [13.42,  3.48],
       [ 8.58,  1.92],
       [15.98,  3.  ],
       [13.42,  1.58],
       [16.27,  2.5 ],
       [10.09,  2.  ],
       [20.45,  3.  ],
       [13.28,  2.72],
       [22.12,  2.88],
       [24.01,  2.  ],
       [15.69,  3.  ],
       [11.61,  3.39],
       [10.77,  1.47],
       [15.53,  3.  ],
       [10.07,  1.25],
       [12.6 ,  1.  ],
       [32.83,  1.17],
       [35.83,  4.67],
       [29.03,  5.92],
       [27.18,  2.  ],
       [22.67,  2.  ],
       [17.82,  1.75],
       [18.78,  3.  ]])

# practice atleast 2 example for each using ndim, shape, size and itemsize

In [26]:
arr = np.array([10, 20, 30, 40])

print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.itemsize)

1
(4,)
4
8

In [27]:

arr1 = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(arr1.itemsize)

2
(2, 3)
6
8

# change data type and memory size of any np-array using astype()

In [28]:
arr1.dtype

dtype('int64')

In [29]:
arr1.astype(np.int32)

array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)

# create 2 same dimensional array and do scalar and vector operations

In [30]:
a1=np.arange(16).reshape(4,4)
a2=np.arange(16,32).reshape(4,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
a2

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [32]:
a1+a2

array([[16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [33]:
a2-a1

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [34]:
a1*a2

array([[  0,  17,  36,  57],
       [ 80, 105, 132, 161],
       [192, 225, 260, 297],
       [336, 377, 420, 465]])

In [35]:
a1/a2

array([[0.        , 0.05882353, 0.11111111, 0.15789474],
       [0.2       , 0.23809524, 0.27272727, 0.30434783],
       [0.33333333, 0.36      , 0.38461538, 0.40740741],
       [0.42857143, 0.44827586, 0.46666667, 0.48387097]])

In [36]:
a1+5

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [37]:
a2-6

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [38]:
a1*3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33],
       [36, 39, 42, 45]])

In [39]:
a2**2

array([[256, 289, 324, 361],
       [400, 441, 484, 529],
       [576, 625, 676, 729],
       [784, 841, 900, 961]])

# find minimun and maximum tip

In [40]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [41]:
tips.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [42]:
np.min(tips['tip'])

1.0

In [43]:
np.max(tips['tip'])

10.0

# find average total_bill and average tip

In [44]:
print(np.mean(tips['total_bill']))
print(np.mean(tips['tip']))

19.78594262295082
2.99827868852459

# find median total_bill

In [45]:
np.median(tips['total_bill'])

np.float64(17.795)

# find standard deviasion and variance of tip

In [46]:
print(np.std(tips['tip']))
print(np.var(tips['tip']))

1.3807999538298958
1.9066085124966428

# find log values of tip

In [47]:
np.log(tips['tip']).to_numpy()

array([0.00995033, 0.5068176 , 1.25276297, 1.19694819, 1.28370777,
       1.54968791, 0.69314718, 1.137833  , 0.67294447, 1.17248214,
       0.53649337, 1.60943791, 0.45107562, 1.09861229, 1.10525683,
       1.36609165, 0.51282363, 1.31103188, 1.25276297, 1.20896035,
       1.40609699, 1.01160091, 0.80200159, 2.0255132 , 1.1568812 ,
       0.85015093, 0.69314718, 0.69314718, 1.45861502, 1.09861229,
       0.37156356, 0.91629073, 1.09861229, 0.89608802, 1.18478998,
       1.28093385, 0.69314718, 1.12167756, 0.83724752, 1.60943791,
       0.80647587, 0.93216408, 1.11841492, 0.27763174, 1.7227666 ,
       1.09861229, 1.60943791, 1.79175947, 0.71783979, 1.09861229,
       0.91629073, 0.95551145, 1.64865863, 0.44468582, 1.46787435,
       1.25561604, 1.09861229, 0.40546511, 0.56531381, 1.90657514,
       1.16627094, 0.69314718, 0.68309684, 1.32441896, 0.97077892,
       1.14740245, 0.90421815, 0.        , 0.69813472, 0.73716407,
       0.67803354, 1.09861229, 1.1442228 , 1.60943791, 0.78845736,
       0.22314355, 1.1249296 , 1.38629436, 1.09861229, 0.99694863,
       1.09861229, 1.22377543, 0.60431597, 1.60943791, 0.70803579,
       1.64287269, 0.69314718, 1.38629436, 1.76644166, 1.09861229,
       1.09861229, 1.25276297, 0.        , 1.45861502, 1.178655  ,
       1.5539252 , 1.38629436, 0.40546511, 1.09861229, 0.40546511,
       0.91629073, 1.09861229, 0.91629073, 1.24703229, 1.40609699,
       0.49469624, 1.40118297, 1.45628673, 1.32441896, 1.38629436,
       1.09861229, 0.        , 1.38629436, 0.93609336, 1.38629436,
       1.25276297, 1.62334082, 0.40546511, 0.58778666, 1.07158362,
       0.83724752, 0.51879379, 0.91629073, 0.69314718, 0.9242589 ,
       1.43508453, 0.39204209, 0.69314718, 0.69314718, 0.77932488,
       0.40546511, 1.04027671, 0.40546511, 0.69314718, 1.178655  ,
       0.22314355, 0.69314718, 0.69314718, 0.69314718, 1.01160091,
       1.25276297, 1.90210753, 1.60943791, 1.60943791, 0.83290912,
       0.40546511, 0.3074847 , 0.48858001, 0.54812141, 0.69314718,
       0.91629073, 0.69314718, 1.00795792, 0.69314718, 0.69314718,
       1.63705308, 1.60943791, 1.32175584, 0.95935022, 0.69314718,
       1.25276297, 0.91629073, 0.69314718, 0.69314718, 1.09861229,
       1.24703229, 0.80647587, 1.5040774 , 0.47623418, 0.69314718,
       2.30258509, 1.15057203, 1.63899671, 1.1568812 , 1.38629436,
       1.13462273, 0.69314718, 0.69314718, 1.38629436, 1.2669476 ,
       1.30291275, 1.73165555, 1.25276297, 1.87180218, 1.09861229,
       1.60943791, 1.25276297, 0.69314718, 1.25276297, 1.38629436,
       0.40546511, 1.43270073, 0.94000726, 0.70309751, 1.38629436,
       0.36464311, 0.69314718, 1.60943791, 0.69314718, 0.69314718,
       1.38629436, 0.69813472, 0.69314718, 0.91629073, 1.38629436,
       1.17248214, 1.22671229, 1.09861229, 0.70803579, 0.80200159,
       0.69314718, 1.64093658, 2.19722458, 0.91629073, 1.87180218,
       0.09531018, 1.09861229, 0.40546511, 0.36464311, 1.12817109,
       0.78845736, 1.24703229, 0.65232519, 1.09861229, 0.45742485,
       0.91629073, 0.69314718, 1.09861229, 1.00063188, 1.05779029,
       0.69314718, 1.09861229, 1.22082992, 0.3852624 , 1.09861229,
       0.22314355, 0.        , 0.15700375, 1.54115907, 1.77833645,
       0.69314718, 0.69314718, 0.55961579, 1.09861229])

# apply round, floor and ceil operation on tip array

In [48]:
np.round(tips['tip']).to_numpy()

array([ 1.,  2.,  4.,  3.,  4.,  5.,  2.,  3.,  2.,  3.,  2.,  5.,  2.,
        3.,  3.,  4.,  2.,  4.,  4.,  3.,  4.,  3.,  2.,  8.,  3.,  2.,
        2.,  2.,  4.,  3.,  1.,  2.,  3.,  2.,  3.,  4.,  2.,  3.,  2.,
        5.,  2.,  3.,  3.,  1.,  6.,  3.,  5.,  6.,  2.,  3.,  2.,  3.,
        5.,  2.,  4.,  4.,  3.,  2.,  2.,  7.,  3.,  2.,  2.,  4.,  3.,
        3.,  2.,  1.,  2.,  2.,  2.,  3.,  3.,  5.,  2.,  1.,  3.,  4.,
        3.,  3.,  3.,  3.,  2.,  5.,  2.,  5.,  2.,  4.,  6.,  3.,  3.,
        4.,  1.,  4.,  3.,  5.,  4.,  2.,  3.,  2.,  2.,  3.,  2.,  3.,
        4.,  2.,  4.,  4.,  4.,  4.,  3.,  1.,  4.,  3.,  4.,  4.,  5.,
        2.,  2.,  3.,  2.,  2.,  2.,  2.,  3.,  4.,  1.,  2.,  2.,  2.,
        2.,  3.,  2.,  2.,  3.,  1.,  2.,  2.,  2.,  3.,  4.,  7.,  5.,
        5.,  2.,  2.,  1.,  2.,  2.,  2.,  2.,  2.,  3.,  2.,  2.,  5.,
        5.,  4.,  3.,  2.,  4.,  2.,  2.,  2.,  3.,  3.,  2.,  4.,  2.,
        2., 10.,  3.,  5.,  3.,  4.,  3.,  2.,  2.,  4.,  4.,  4.,  6.,
        4.,  6.,  3.,  5.,  4.,  2.,  4.,  4.,  2.,  4.,  3.,  2.,  4.,
        1.,  2.,  5.,  2.,  2.,  4.,  2.,  2.,  2.,  4.,  3.,  3.,  3.,
        2.,  2.,  2.,  5.,  9.,  2.,  6.,  1.,  3.,  2.,  1.,  3.,  2.,
        3.,  2.,  3.,  2.,  2.,  2.,  3.,  3.,  3.,  2.,  3.,  3.,  1.,
        3.,  1.,  1.,  1.,  5.,  6.,  2.,  2.,  2.,  3.])

In [49]:
np.floor(tips['tip']).to_numpy()

array([ 1.,  1.,  3.,  3.,  3.,  4.,  2.,  3.,  1.,  3.,  1.,  5.,  1.,
        3.,  3.,  3.,  1.,  3.,  3.,  3.,  4.,  2.,  2.,  7.,  3.,  2.,
        2.,  2.,  4.,  3.,  1.,  2.,  3.,  2.,  3.,  3.,  2.,  3.,  2.,
        5.,  2.,  2.,  3.,  1.,  5.,  3.,  5.,  6.,  2.,  3.,  2.,  2.,
        5.,  1.,  4.,  3.,  3.,  1.,  1.,  6.,  3.,  2.,  1.,  3.,  2.,
        3.,  2.,  1.,  2.,  2.,  1.,  3.,  3.,  5.,  2.,  1.,  3.,  4.,
        3.,  2.,  3.,  3.,  1.,  5.,  2.,  5.,  2.,  4.,  5.,  3.,  3.,
        3.,  1.,  4.,  3.,  4.,  4.,  1.,  3.,  1.,  2.,  3.,  2.,  3.,
        4.,  1.,  4.,  4.,  3.,  4.,  3.,  1.,  4.,  2.,  4.,  3.,  5.,
        1.,  1.,  2.,  2.,  1.,  2.,  2.,  2.,  4.,  1.,  2.,  2.,  2.,
        1.,  2.,  1.,  2.,  3.,  1.,  2.,  2.,  2.,  2.,  3.,  6.,  5.,
        5.,  2.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,  5.,
        5.,  3.,  2.,  2.,  3.,  2.,  2.,  2.,  3.,  3.,  2.,  4.,  1.,
        2., 10.,  3.,  5.,  3.,  4.,  3.,  2.,  2.,  4.,  3.,  3.,  5.,
        3.,  6.,  3.,  5.,  3.,  2.,  3.,  4.,  1.,  4.,  2.,  2.,  4.,
        1.,  2.,  5.,  2.,  2.,  4.,  2.,  2.,  2.,  4.,  3.,  3.,  3.,
        2.,  2.,  2.,  5.,  9.,  2.,  6.,  1.,  3.,  1.,  1.,  3.,  2.,
        3.,  1.,  3.,  1.,  2.,  2.,  3.,  2.,  2.,  2.,  3.,  3.,  1.,
        3.,  1.,  1.,  1.,  4.,  5.,  2.,  2.,  1.,  3.])

In [50]:
np.ceil(tips['tip']).to_numpy()

array([ 2.,  2.,  4.,  4.,  4.,  5.,  2.,  4.,  2.,  4.,  2.,  5.,  2.,
        3.,  4.,  4.,  2.,  4.,  4.,  4.,  5.,  3.,  3.,  8.,  4.,  3.,
        2.,  2.,  5.,  3.,  2.,  3.,  3.,  3.,  4.,  4.,  2.,  4.,  3.,
        5.,  3.,  3.,  4.,  2.,  6.,  3.,  5.,  6.,  3.,  3.,  3.,  3.,
        6.,  2.,  5.,  4.,  3.,  2.,  2.,  7.,  4.,  2.,  2.,  4.,  3.,
        4.,  3.,  1.,  3.,  3.,  2.,  3.,  4.,  5.,  3.,  2.,  4.,  4.,
        3.,  3.,  3.,  4.,  2.,  5.,  3.,  6.,  2.,  4.,  6.,  3.,  3.,
        4.,  1.,  5.,  4.,  5.,  4.,  2.,  3.,  2.,  3.,  3.,  3.,  4.,
        5.,  2.,  5.,  5.,  4.,  4.,  3.,  1.,  4.,  3.,  4.,  4.,  6.,
        2.,  2.,  3.,  3.,  2.,  3.,  2.,  3.,  5.,  2.,  2.,  2.,  3.,
        2.,  3.,  2.,  2.,  4.,  2.,  2.,  2.,  2.,  3.,  4.,  7.,  5.,
        5.,  3.,  2.,  2.,  2.,  2.,  2.,  3.,  2.,  3.,  2.,  2.,  6.,
        5.,  4.,  3.,  2.,  4.,  3.,  2.,  2.,  3.,  4.,  3.,  5.,  2.,
        2., 10.,  4.,  6.,  4.,  4.,  4.,  2.,  2.,  4.,  4.,  4.,  6.,
        4.,  7.,  3.,  5.,  4.,  2.,  4.,  4.,  2.,  5.,  3.,  3.,  4.,
        2.,  2.,  5.,  2.,  2.,  4.,  3.,  2.,  3.,  4.,  4.,  4.,  3.,
        3.,  3.,  2.,  6.,  9.,  3.,  7.,  2.,  3.,  2.,  2.,  4.,  3.,
        4.,  2.,  3.,  2.,  3.,  2.,  3.,  3.,  3.,  2.,  3.,  4.,  2.,
        3.,  2.,  1.,  2.,  5.,  6.,  2.,  2.,  2.,  3.])

# use 1D, 2D and 3D np-array, and apply indexing and slicing atleast 5 example for each (take example as your wish)

In [51]:
a1= np.array([10, 20, 30, 40, 50, 60, 70])
print(a1[0])
print(a1[-1])
print(a1[0:4])
print(a1[2:6:2])
print(a1[::-1])

10
70
[10 20 30 40]
[30 50]
[70 60 50 40 30 20 10]

In [52]:
a2 = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])
print(a2[0])
print(a2[:2, :])
print(a2[2:, :])
print(a2[:, :2])
print(a2[:, 2:])

[10 20 30 40]
[[10 20 30 40]
 [50 60 70 80]]
[[ 90 100 110 120]
 [130 140 150 160]]
[[ 10  20]
 [ 50  60]
 [ 90 100]
 [130 140]]
[[ 30  40]
 [ 70  80]
 [110 120]
 [150 160]]

In [53]:
a3 = np.arange(24).reshape(2, 3, 4)
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [54]:
print(a3[:, :, :2])
print(a3[0, 1:, :])
print(a3[1, :2, 2:])
print(a3[:, :, ::2])
print(a3[::-1, ::-1, ::-1])

[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[12 13]
  [16 17]
  [20 21]]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[14 15]
 [18 19]]
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[12 14]
  [16 18]
  [20 22]]]
[[[23 22 21 20]
  [19 18 17 16]
  [15 14 13 12]]

 [[11 10  9  8]
  [ 7  6  5  4]
  [ 3  2  1  0]]]

# stacking and spliting

In [55]:
d = np.arange(27).reshape(3,9)
e = np.arange(28,55).reshape(3,9)

In [56]:
np.stack((d, e))

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]],

       [[28, 29, 30, 31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50, 51, 52, 53, 54]]])

In [57]:
 np.split(d, 3, axis=0)

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [58]:
 np.split(e, 3, axis=0)

[array([[28, 29, 30, 31, 32, 33, 34, 35, 36]]),
 array([[37, 38, 39, 40, 41, 42, 43, 44, 45]]),
 array([[46, 47, 48, 49, 50, 51, 52, 53, 54]])]

# use hstack() and vstack()

In [59]:
np.hstack((d, e))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8, 28, 29, 30, 31, 32, 33, 34,
        35, 36],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 37, 38, 39, 40, 41, 42, 43,
        44, 45],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 46, 47, 48, 49, 50, 51, 52,
        53, 54]])

In [60]:
np.vstack((d, e))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54]])

# use hsplit() and vsplit()

In [61]:
np.vsplit(d, 3)

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [62]:
np.hsplit(e, 3)

[array([[28, 29, 30],
        [37, 38, 39],
        [46, 47, 48]]),
 array([[31, 32, 33],
        [40, 41, 42],
        [49, 50, 51]]),
 array([[34, 35, 36],
        [43, 44, 45],
        [52, 53, 54]])]